# Repo: Demo/Demo.Templates

parameters:
  vmImage: 'ubuntu 16.04'

jobs:
- job: Build
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - script: echo "This step is from the Demo.Templates repo"